"""AUTO-GENERATED by generate_model_constants.py — do not hand-edit.
Re-run the generator after retraining the model (model/train.py).
"""

FEATURE_ORDER = ["hour", "day_of_week", "is_weekend", "is_night", "log_amount", "amount_vs_avg_ratio", "is_large_txn", "is_round_amount", "sender_account_age_days", "receiver_account_age_days", "is_new_sender_acc", "is_new_receiver_acc", "account_age_diff", "sender_txn_count_7d", "receiver_txn_count_7d", "txn_velocity_ratio", "high_sender_velocity", "sender_avg_amount_30d", "is_new_device", "is_new_beneficiary", "failed_attempts_24h", "failed_attempt_risk", "device_change_30d", "device_change_risk", "cross_state", "foreign_ip", "multi_risk_flag", "sender_upi_app", "receiver_upi_app", "sender_bank", "receiver_bank", "merchant_category", "sender_state", "receiver_state", "ip_country"]

FEATURE_OWNER = {
    "hour": "GATEWAY",
    "day_of_week": "GATEWAY",
    "is_weekend": "GATEWAY",
    "is_night": "GATEWAY",
    "log_amount": "GATEWAY",
    "is_large_txn": "GATEWAY",
    "is_round_amount": "GATEWAY",
    "is_new_device": "GATEWAY",
    "device_change_30d": "GATEWAY",
    "device_change_risk": "GATEWAY",
    "foreign_ip": "GATEWAY",
    "sender_bank": "GATEWAY",
    "receiver_bank": "GATEWAY",
    "merchant_category": "GATEWAY",
    "ip_country": "GATEWAY",
    "sender_account_age_days": "SENDER",
    "is_new_sender_acc": "SENDER",
    "sender_txn_count_7d": "SENDER",
    "sender_avg_amount_30d": "SENDER",
    "high_sender_velocity": "SENDER",
    "sender_upi_app": "SENDER",
    "sender_state": "SENDER",
    "is_new_beneficiary": "SENDER",
    "receiver_account_age_days": "RECEIVER",
    "is_new_receiver_acc": "RECEIVER",
    "receiver_txn_count_7d": "RECEIVER",
    "receiver_upi_app": "RECEIVER",
    "receiver_state": "RECEIVER",
    "failed_attempts_24h": "NPCI",
    "failed_attempt_risk": "NPCI",
    "amount_vs_avg_ratio": "DERIVED",
    "account_age_diff": "DERIVED",
    "txn_velocity_ratio": "DERIVED",
    "cross_state": "DERIVED",
    "multi_risk_flag": "DERIVED"
}

# folded_weight_i = coef_i / scaler.scale_i  (see module docstring)
FOLDED_WEIGHTS = {
    "hour": -0.0025886497341952005,
    "day_of_week": -0.04667277140440503,
    "is_weekend": 0.1664809822156929,
    "is_night": -0.05209586505991258,
    "log_amount": 0.2323119987505693,
    "amount_vs_avg_ratio": -0.0010962403423339121,
    "is_large_txn": 1.2432775104360911,
    "is_round_amount": 0.06763831665217901,
    "sender_account_age_days": -0.00016089571077136406,
    "receiver_account_age_days": -0.00025836971523550075,
    "is_new_sender_acc": -0.2592984025697032,
    "is_new_receiver_acc": 0.7727077622295007,
    "account_age_diff": -0.00010548661069205292,
    "sender_txn_count_7d": -0.03661185505376214,
    "receiver_txn_count_7d": 0.0011475890960469047,
    "txn_velocity_ratio": 0.7772340193851508,
    "high_sender_velocity": 8.348471914054606,
    "sender_avg_amount_30d": -1.0998078855653487e-05,
    "is_new_device": 0.27462047920616844,
    "is_new_beneficiary": 0.3145157034202765,
    "failed_attempts_24h": 0.4834993229143914,
    "failed_attempt_risk": -0.4522411455550227,
    "device_change_30d": 0.35925797821026023,
    "device_change_risk": -0.11456706242879938,
    "cross_state": -0.050947885913013635,
    "foreign_ip": 0.10883646590101463,
    "multi_risk_flag": 0.22313936367004705,
    "sender_upi_app": 0.02508309294573899,
    "receiver_upi_app": -0.0010309980409433609,
    "sender_bank": -0.00938970580794488,
    "receiver_bank": -0.00580049054925756,
    "merchant_category": -0.020324760424853663,
    "sender_state": -0.0019537766364637293,
    "receiver_state": -0.004347988590388653,
    "ip_country": -0.10883646590097384
}

FOLDED_BIAS = -4.645039578465182

# logit >= LOGIT_THRESHOLD  <=>  sigmoid(logit) >= PROBA_THRESHOLD
LOGIT_THRESHOLD = -0.8907923200982515
PROBA_THRESHOLD = 0.290946347445139

# LabelEncoder.classes_ for every categorical column, so any node can
# reproduce the exact same integer encoding the model was trained on.
ENCODER_CLASSES = {
    "sender_upi_app": [
        "Amazon Pay",
        "BHIM",
        "GPay",
        "Paytm",
        "PhonePe",
        "WhatsApp Pay"
    ],
    "receiver_upi_app": [
        "Amazon Pay",
        "BHIM",
        "GPay",
        "Paytm",
        "PhonePe",
        "WhatsApp Pay"
    ],
    "sender_bank": [
        "Axis",
        "BOB",
        "Canara",
        "HDFC",
        "ICICI",
        "Kotak",
        "PNB",
        "SBI"
    ],
    "receiver_bank": [
        "Axis",
        "BOB",
        "Canara",
        "HDFC",
        "ICICI",
        "Kotak",
        "PNB",
        "SBI"
    ],
    "merchant_category": [
        "Bill",
        "Entertainment",
        "Food",
        "Grocery",
        "Medical",
        "Shopping",
        "Transfer",
        "Travel"
    ],
    "sender_state": [
        "Delhi",
        "Gujarat",
        "Karnataka",
        "MP",
        "Maharashtra",
        "Rajasthan",
        "Tamil Nadu",
        "Telangana",
        "UP",
        "West Bengal"
    ],
    "receiver_state": [
        "Delhi",
        "Gujarat",
        "Karnataka",
        "MP",
        "Maharashtra",
        "Rajasthan",
        "Tamil Nadu",
        "Telangana",
        "UP",
        "West Bengal"
    ],
    "ip_country": [
        "Foreign",
        "India"
    ]
}
