import json
import os
from pathlib import Path

import joblib
import numpy as np

AI_ARTIFACTS_DIR = Path(
    os.environ.get(
        "AI_ARTIFACTS_DIR",
        Path(__file__).resolve().parents[2] / "AI" / "AI" / "fixed" / "artifacts",
    )
)
OUT_PATH = Path(__file__).parent / "model_constants.py"

FEATURE_OWNER = {
    "hour": "GATEWAY", "day_of_week": "GATEWAY", "is_weekend": "GATEWAY",
    "is_night": "GATEWAY", "log_amount": "GATEWAY", "is_large_txn": "GATEWAY",
    "is_round_amount": "GATEWAY", "is_new_device": "GATEWAY",
    "device_change_30d": "GATEWAY", "device_change_risk": "GATEWAY",
    "foreign_ip": "GATEWAY", "sender_bank": "GATEWAY", "receiver_bank": "GATEWAY",
    "merchant_category": "GATEWAY", "ip_country": "GATEWAY",

    "sender_account_age_days": "SENDER", "is_new_sender_acc": "SENDER",
    "sender_txn_count_7d": "SENDER", "sender_avg_amount_30d": "SENDER",
    "high_sender_velocity": "SENDER", "sender_upi_app": "SENDER",
    "sender_state": "SENDER", "is_new_beneficiary": "SENDER",

    "receiver_account_age_days": "RECEIVER", "is_new_receiver_acc": "RECEIVER",
    "receiver_txn_count_7d": "RECEIVER", "receiver_upi_app": "RECEIVER",
    "receiver_state": "RECEIVER",

    "failed_attempts_24h": "NPCI", "failed_attempt_risk": "NPCI",

    "amount_vs_avg_ratio": "DERIVED", "account_age_diff": "DERIVED",
    "txn_velocity_ratio": "DERIVED", "cross_state": "DERIVED",
    "multi_risk_flag": "DERIVED",
}

def main():
    model = joblib.load(AI_ARTIFACTS_DIR / "lr_model.joblib")
    scaler = joblib.load(AI_ARTIFACTS_DIR / "scaler.joblib")
    meta = joblib.load(AI_ARTIFACTS_DIR / "threshold.joblib")
    encoders = joblib.load(AI_ARTIFACTS_DIR / "label_encoders.joblib")

    cols = meta["feature_cols"]
    missing = set(cols) - set(FEATURE_OWNER)
    extra = set(FEATURE_OWNER) - set(cols)
    if missing:
        raise SystemExit(f"FEATURE_OWNER is missing: {sorted(missing)}")
    if extra:
        raise SystemExit(f"FEATURE_OWNER has stale entries not in the model: {sorted(extra)}")

    coef = model.coef_[0]
    intercept = float(model.intercept_[0])
    mean = scaler.mean_
    scale = scaler.scale_
    threshold = float(meta["threshold"])

    folded_weights = coef / scale
    folded_bias = float(intercept - np.sum(coef * mean / scale))
    logit_threshold = float(np.log(threshold / (1 - threshold)))

    rng = np.random.default_rng(0)
    z = rng.normal(size=(500, len(cols)))
    x = z * scale + mean
    proba_ref = model.predict_proba((x - mean) / scale)[:, 1]
    logit_folded = x @ folded_weights + folded_bias
    assert np.array_equal(proba_ref >= threshold, logit_folded >= logit_threshold), (
        "folded weights do not reproduce the trained model's decisions — "
        "do not trust the generated .mpc script until this passes"
    )

    encoder_classes = {name: list(le.classes_) for name, le in encoders.items()}

    lines = [
        '"""AUTO-GENERATED by generate_model_constants.py — do not hand-edit.',
        "Re-run the generator after retraining the model (model/train.py).",
        '"""',
        "",
        f"FEATURE_ORDER = {json.dumps(cols)}",
        "",
        f"FEATURE_OWNER = {json.dumps(FEATURE_OWNER, indent=4)}",
        "",
        "# folded_weight_i = coef_i / scaler.scale_i  (see module docstring)",
        f"FOLDED_WEIGHTS = {json.dumps({c: folded_weights[i] for i, c in enumerate(cols)}, indent=4)}",
        "",
        f"FOLDED_BIAS = {folded_bias!r}",
        "",
        "# logit >= LOGIT_THRESHOLD  <=>  sigmoid(logit) >= PROBA_THRESHOLD",
        f"LOGIT_THRESHOLD = {logit_threshold!r}",
        f"PROBA_THRESHOLD = {threshold!r}",
        "",
        "# LabelEncoder.classes_ for every categorical column, so any node can",
        "# reproduce the exact same integer encoding the model was trained on.",
        f"ENCODER_CLASSES = {json.dumps(encoder_classes, indent=4)}",
        "",
    ]
    OUT_PATH.write_text("\n".join(lines))
    print(f"wrote {OUT_PATH}  ({len(cols)} features, threshold={threshold:.4f}, "
          f"logit_threshold={logit_threshold:.4f})")

if __name__ == "__main__":
    main()
